[build]
  publish = "eventpr/staticfiles"
  command = "chmod +x build.sh && ./build.sh"

[build.environment]
  PYTHON_VERSION = "3.9"
  DJANGO_SETTINGS_MODULE = "eventpr.settings"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/django_app/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
