# Generated by Django 3.2.25 on 2025-07-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0003_auto_20250627_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cus_email',
            field=models.EmailField(default='chundurusai5@gmail.com', max_length=55),
            preserve_default=False,
        ),
    ]
